-- Two source GENERIC templates and three pinned campaign spawns.
-- Source unkInt32 is RequiredLevel: ObjectMgr 22bfd97d, selected field49.
-- Requires optional visual addon columns from 2026_10_05_03.
-- No NPC AI, quest definitions, event scripts or loot are modified.
DROP TEMPORARY TABLE IF EXISTS `_1kycore_level_guard`, `_1kycore_level_templates`, `_1kycore_level_addons`, `_1kycore_level_spawns`;
CREATE TEMPORARY TABLE `_1kycore_level_guard` (ok INT PRIMARY KEY);
INSERT INTO `_1kycore_level_guard` VALUES (1);
CREATE TEMPORARY TABLE `_1kycore_level_templates` LIKE `gameobject_template`;
INSERT INTO `_1kycore_level_templates` (`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`size`,`Data0`,`Data1`,`Data2`,`Data3`,`Data4`,`Data5`,`Data6`,`Data7`,`Data8`,`Data9`,`Data10`,`Data11`,`Data12`,`Data13`,`Data14`,`Data15`,`Data16`,`Data17`,`Data18`,`Data19`,`Data20`,`Data21`,`Data22`,`Data23`,`Data24`,`Data25`,`Data26`,`Data27`,`Data28`,`Data29`,`Data30`,`Data31`,`Data32`,`RequiredLevel`,`AIName`,`ScriptName`,`VerifiedBuild`) VALUES
(269053,5,28299,'Box','questinteract','','',1.2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,'','',1),
(269055,5,31903,'Banner','','','',1.2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,'','',1);
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM `gameobject_template` a JOIN `_1kycore_level_templates` n ON a.`entry`=n.`entry` WHERE NOT (a.`type` <=> n.`type` AND a.`displayId` <=> n.`displayId` AND BINARY a.`name` <=> BINARY n.`name` AND BINARY a.`IconName` <=> BINARY n.`IconName` AND BINARY a.`castBarCaption` <=> BINARY n.`castBarCaption` AND BINARY a.`unk1` <=> BINARY n.`unk1` AND ABS(a.`size`-n.`size`)<=0.000001 AND a.`Data0` <=> n.`Data0` AND a.`Data1` <=> n.`Data1` AND a.`Data2` <=> n.`Data2` AND a.`Data3` <=> n.`Data3` AND a.`Data4` <=> n.`Data4` AND a.`Data5` <=> n.`Data5` AND a.`Data6` <=> n.`Data6` AND a.`Data7` <=> n.`Data7` AND a.`Data8` <=> n.`Data8` AND a.`Data9` <=> n.`Data9` AND a.`Data10` <=> n.`Data10` AND a.`Data11` <=> n.`Data11` AND a.`Data12` <=> n.`Data12` AND a.`Data13` <=> n.`Data13` AND a.`Data14` <=> n.`Data14` AND a.`Data15` <=> n.`Data15` AND a.`Data16` <=> n.`Data16` AND a.`Data17` <=> n.`Data17` AND a.`Data18` <=> n.`Data18` AND a.`Data19` <=> n.`Data19` AND a.`Data20` <=> n.`Data20` AND a.`Data21` <=> n.`Data21` AND a.`Data22` <=> n.`Data22` AND a.`Data23` <=> n.`Data23` AND a.`Data24` <=> n.`Data24` AND a.`Data25` <=> n.`Data25` AND a.`Data26` <=> n.`Data26` AND a.`Data27` <=> n.`Data27` AND a.`Data28` <=> n.`Data28` AND a.`Data29` <=> n.`Data29` AND a.`Data30` <=> n.`Data30` AND a.`Data31` <=> n.`Data31` AND a.`Data32` <=> n.`Data32` AND a.`RequiredLevel` <=> n.`RequiredLevel` AND BINARY a.`AIName` <=> BINARY n.`AIName` AND BINARY a.`ScriptName` <=> BINARY n.`ScriptName`) LIMIT 1;
CREATE TEMPORARY TABLE `_1kycore_level_addons` LIKE `gameobject_template_addon`;
INSERT INTO `_1kycore_level_addons` (`entry`,`faction`,`flags`,`mingold`,`maxgold`,`WorldEffectID`,`SpellVisualID`,`SpellStateVisualID`,`StateWorldEffectID`) VALUES
(269053,0,0,0,0,0,0,0,0),
(269055,0,0,0,0,0,0,0,0);
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM `gameobject_template_addon` a JOIN `_1kycore_level_addons` n ON a.`entry`=n.`entry` WHERE NOT (a.`faction` <=> n.`faction` AND a.`flags` <=> n.`flags` AND a.`mingold` <=> n.`mingold` AND a.`maxgold` <=> n.`maxgold` AND a.`WorldEffectID` <=> n.`WorldEffectID` AND a.`SpellVisualID` <=> n.`SpellVisualID` AND a.`SpellStateVisualID` <=> n.`SpellStateVisualID` AND a.`StateWorldEffectID` <=> n.`StateWorldEffectID`) LIMIT 1;
CREATE TEMPORARY TABLE `_1kycore_level_spawns` LIKE `gameobject`;
INSERT INTO `_1kycore_level_spawns` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnDifficulties`,`phaseUseFlags`,`PhaseId`,`PhaseGroup`,`terrainSwapMap`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`animprogress`,`state`,`isActive`,`ScriptName`,`VerifiedBuild`) VALUES
(210304716,269053,1220,7543,8548,'0',0,5632,0,-1,-704.094,2103.5,-0.983894,4.77193,180,0.0,0.0,0.0,1.0,255,1,0,'',0),
(210304717,269055,1220,7543,8548,'0',0,5632,0,-1,-705.793,2108.51,0.521985,4.21365,180,0.0,0.0,0.0,1.0,255,1,0,'',0),
(210304718,269053,1220,7543,8548,'0',0,5632,0,-1,-706.118,2108.31,-1.02362,3.479,180,0.0,0.0,0.0,1.0,255,1,0,'',0);
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM `gameobject` a JOIN `_1kycore_level_spawns` n ON a.`guid`=n.`guid` WHERE NOT (a.`id` <=> n.`id` AND a.`map` <=> n.`map` AND a.`zoneId` <=> n.`zoneId` AND a.`areaId` <=> n.`areaId` AND BINARY a.`spawnDifficulties` <=> BINARY n.`spawnDifficulties` AND a.`phaseUseFlags` <=> n.`phaseUseFlags` AND a.`PhaseId` <=> n.`PhaseId` AND a.`PhaseGroup` <=> n.`PhaseGroup` AND a.`terrainSwapMap` <=> n.`terrainSwapMap` AND ABS(a.`position_x`-n.`position_x`)<=0.000001 AND ABS(a.`position_y`-n.`position_y`)<=0.000001 AND ABS(a.`position_z`-n.`position_z`)<=0.000001 AND ABS(a.`orientation`-n.`orientation`)<=0.000001 AND a.`spawntimesecs` <=> n.`spawntimesecs` AND ABS(a.`rotation0`-n.`rotation0`)<=0.000001 AND ABS(a.`rotation1`-n.`rotation1`)<=0.000001 AND ABS(a.`rotation2`-n.`rotation2`)<=0.000001 AND ABS(a.`rotation3`-n.`rotation3`)<=0.000001 AND a.`animprogress` <=> n.`animprogress` AND a.`state` <=> n.`state` AND a.`isActive` <=> n.`isActive` AND BINARY a.`ScriptName` <=> BINARY n.`ScriptName`) LIMIT 1;
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM gameobject_questitem WHERE GameObjectEntry IN(269053,269055) LIMIT 1;
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM smart_scripts WHERE source_type=1 AND (entryorguid IN(269053,269055) OR entryorguid IN(SELECT -CAST(guid AS SIGNED) FROM `_1kycore_level_spawns`) OR entryorguid IN(SELECT -CAST(guid AS SIGNED) FROM gameobject WHERE id IN(269053,269055))) LIMIT 1;
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM conditions WHERE SourceEntry IN(269053,269055) LIMIT 1;
INSERT INTO `_1kycore_level_guard` SELECT 1 FROM gameobject_template t JOIN `_1kycore_level_templates` n ON t.entry=n.entry LEFT JOIN gameobject_template_addon a ON a.entry=t.entry WHERE a.entry IS NULL LIMIT 1;
INSERT INTO `gameobject_template_addon` (`entry`,`faction`,`flags`,`mingold`,`maxgold`,`WorldEffectID`,`SpellVisualID`,`SpellStateVisualID`,`StateWorldEffectID`) SELECT n.`entry`,n.`faction`,n.`flags`,n.`mingold`,n.`maxgold`,n.`WorldEffectID`,n.`SpellVisualID`,n.`SpellStateVisualID`,n.`StateWorldEffectID` FROM `_1kycore_level_addons` n LEFT JOIN `gameobject_template_addon` a ON a.`entry`=n.`entry` WHERE a.`entry` IS NULL;
INSERT INTO `gameobject_template` (`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`size`,`Data0`,`Data1`,`Data2`,`Data3`,`Data4`,`Data5`,`Data6`,`Data7`,`Data8`,`Data9`,`Data10`,`Data11`,`Data12`,`Data13`,`Data14`,`Data15`,`Data16`,`Data17`,`Data18`,`Data19`,`Data20`,`Data21`,`Data22`,`Data23`,`Data24`,`Data25`,`Data26`,`Data27`,`Data28`,`Data29`,`Data30`,`Data31`,`Data32`,`RequiredLevel`,`AIName`,`ScriptName`,`VerifiedBuild`) SELECT n.`entry`,n.`type`,n.`displayId`,n.`name`,n.`IconName`,n.`castBarCaption`,n.`unk1`,n.`size`,n.`Data0`,n.`Data1`,n.`Data2`,n.`Data3`,n.`Data4`,n.`Data5`,n.`Data6`,n.`Data7`,n.`Data8`,n.`Data9`,n.`Data10`,n.`Data11`,n.`Data12`,n.`Data13`,n.`Data14`,n.`Data15`,n.`Data16`,n.`Data17`,n.`Data18`,n.`Data19`,n.`Data20`,n.`Data21`,n.`Data22`,n.`Data23`,n.`Data24`,n.`Data25`,n.`Data26`,n.`Data27`,n.`Data28`,n.`Data29`,n.`Data30`,n.`Data31`,n.`Data32`,n.`RequiredLevel`,n.`AIName`,n.`ScriptName`,n.`VerifiedBuild` FROM `_1kycore_level_templates` n LEFT JOIN `gameobject_template` a ON a.`entry`=n.`entry` WHERE a.`entry` IS NULL;
INSERT INTO `gameobject` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnDifficulties`,`phaseUseFlags`,`PhaseId`,`PhaseGroup`,`terrainSwapMap`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`animprogress`,`state`,`isActive`,`ScriptName`,`VerifiedBuild`) SELECT n.`guid`,n.`id`,n.`map`,n.`zoneId`,n.`areaId`,n.`spawnDifficulties`,n.`phaseUseFlags`,n.`PhaseId`,n.`PhaseGroup`,n.`terrainSwapMap`,n.`position_x`,n.`position_y`,n.`position_z`,n.`orientation`,n.`spawntimesecs`,n.`rotation0`,n.`rotation1`,n.`rotation2`,n.`rotation3`,n.`animprogress`,n.`state`,n.`isActive`,n.`ScriptName`,n.`VerifiedBuild` FROM `_1kycore_level_spawns` n LEFT JOIN `gameobject` a ON a.`guid`=n.`guid` WHERE a.`guid` IS NULL;
DROP TEMPORARY TABLE `_1kycore_level_guard`, `_1kycore_level_templates`, `_1kycore_level_addons`, `_1kycore_level_spawns`;
